FROM grafana/grafana

COPY ./grafana_provisioning/datasources /etc/grafana/provisioning/datasources
COPY ./grafana_provisioning/dashboards /etc/grafana/provisioning/dashboards
COPY ./grafana_provisioning/dashboards_json /var/lib/grafana/dashboards
