{
 "title": "Sales Data",
 "time": { "from": "2024-07-02T23:00:00.000Z", "to": "2024-07-10T22:59:59.000Z" },
 "panels": [
  {
   "title": "Total Revenue per hour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSQL": "SELECT   TO_CHAR(o.date_time, 'HH24:00') AS hour,    SUM(payment_total/100) AS Revenue FROM     orders o GROUP BY     hour ORDER BY    hour;",
     "rawSql": "SELECT   TO_CHAR(o.date_time, 'HH24:00') AS hour,    SUM(payment_total/100) AS Revenue FROM     orders o GROUP BY     hour ORDER BY    hour;",
     "schema": "public"
    }
   ]
  },
  {
   "title": "Total Revenue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSQL": "SELECT    CAST(order_date AS TIMESTAMP) AS time,    SUM(payment_total) / 100 AS revenueFROM    orders GROUP BY    time ORDER BY    time;",
     "rawSql": "SELECT \nCAST(order_date AS TIMESTAMP) AS time,   \n SUM(payment_total) / 100 AS revenue \n FROM    orders GROUP BY    time ORDER BY    time;",
     "schema": "public"
    }
   ]
  },
  {
   "title": "Average Revenue per order per day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSQL": "SELECT (CONVERT(float, AVG(payment_total))/100) AS Revenue, CAST(order_date AS TIMESTAMP) AS time FROM orders GROUP BY time",
     "rawSql": "SELECT AVG(payment_total)/100 AS Revenue, CAST(order_date AS TIMESTAMP) AS time FROM orders GROUP BY time",
     "schema": "public"
    }
   ]
  },
  {
   "title": "Total Revenue At Present Per Branch",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSQL": "SELECT SUM(payment_total/100) AS Revenue, branch_location FROM orders GROUP BY branch_location ORDER BY Revenue  desc",
     "rawSql": "SELECT SUM(payment_total/100) AS Revenue, branch_location FROM orders GROUP BY branch_location ORDER BY Revenue  desc",
     "schema": "public"
    }
   ]
  },
  {
   "title": " Branch Total Revenue over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSQL": "SELECT    CAST(order_date AS TIMESTAMP) AS time,    SUM(payment_total) / 100 AS Sales,  branch_location FROM     orders GROUP BY   branch_location, time ORDER BY   time;",
     "rawSql": "SELECT    CAST(order_date AS TIMESTAMP) AS time,    SUM(payment_total) / 100 AS Sales,  branch_location FROM     orders GROUP BY   branch_location, time ORDER BY   time;"
    }
   ]
  },
  {
   "title": "Product Volume Sold ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSQL": "SELECT COUNT (op.order_products_id) AS products_sold,CAST(o.order_date AS TIMESTAMP) AS time FROM order_products op JOIN orders o ON op.order_id = o.order_id GROUP by time ORDER BY time;",
     "rawSql": "SELECT COUNT (op.order_products_id) AS products_sold,CAST(o.order_date AS TIMESTAMP) AS time FROM order_products op JOIN orders o ON op.order_id = o.order_id GROUP by time ORDER BY time;",
     "schema": "public"
    }
   ]
  },
  {
   "title": "Products Volume By Branch",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSQL": "SELECT COUNT (op.order_products_id) AS products, o.branch_location\r\nFrom order_products op\r\nJOIN orders o\r\nON op.order_id = o.order_id\r\nGROUP BY branch_location\r\norder by products desc",
     "rawSql": "SELECT COUNT (op.order_products_id) AS products, o.branch_location\nFrom order_products op\nJOIN orders o\nON op.order_id = o.order_id\n\nGROUP BY branch_location order by products desc",
     "schema": "public"
    }
   ]
  },
  {
   "title": "Total products sold over time per product",
   "type": "timeseries",
   "description": "Total product volume over time per product",
   "gridPos": { "h": 13, "w": 22, "x": 0, "y": 59 },
   "targets": [
    {
     "rawSQL": "SELECT\r\n    p.name,\r\n    CAST(o.order_date AS TIMESTAMP) AS time,\r\n    COUNT(op.order_products_id) AS sales\r\nFROM\r\n    order_products op\r\nJOIN\r\n    orders o ON op.order_id = o.order_id\r\nJOIN\r\n    products p ON op.product_id = p.product_id\r\nGROUP BY\r\n    p.name, time\r\nORDER BY\r\n    time;",
     "rawSql": "SELECT     p.name,     CAST(o.order_date AS TIMESTAMP) AS time,     COUNT(op.order_products_id) AS sales FROM     order_products op JOIN     orders o ON op.order_id = o.order_id JOIN     products p ON op.product_id = p.product_id GROUP BY     p.name, time ORDER BY     time;",
     "schema": "public"
    }
   ]
  },
  {
   "title": "Product Volume per Hour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 72 },
   "targets": [
    {
     "rawSQL": "SELECT\n    TO_CHAR(o.date_time, 'HH24:00') AS hour,\n    Count(op.order_products_id) AS volume\nFROM\n    orders o\nJOIN order_products op ON o.order_id = op.order_id\nGROUP BY\n    hour\nORDER BY\n    hour;",
     "rawSql": "SELECT     TO_CHAR(o.date_time, 'HH24:00') AS hour,     Count(op.order_products_id) AS volume FROM     orders o JOIN order_products op ON o.order_id = op.order_id GROUP BY     hour ORDER BY     hour;",
     "schema": "public"
    }
   ]
  },
  {
   "title": "Product sold per size per day ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 80 },
   "targets": [
    {
     "rawSQL": "SELECT \n  p.size,\n  COUNT(op.product_id) AS Sold,\n  CAST(o.order_date AS TIMESTAMP) AS time\nFROM \n  order_products op\njoin\n  products p on op.product_id = p.product_id\njoin\n  orders o on op.order_id = o.order_id\nGroup by\n  p.size, time\nORDER BY\n  time ASC",
     "rawSql": "SELECT    p.size,   COUNT(op.product_id) AS Sold,   CAST(o.order_date AS TIMESTAMP) AS time FROM    order_products op join   products p on op.product_id = p.product_id join   orders o on op.order_id = o.order_id Group by   p.size, time ORDER BY   time ASC",
     "schema": "public"
    }
   ]
  }
 ]
}