{
 "title": "Branch Dashboard",
 "time": { "from": "2024-07-02T23:00:00.000Z", "to": "2024-07-10T22:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "Branch",
    "label": "Branch",
    "query": "SELECT DISTINCT branch_location From orders"
   }
  ]
 },
 "panels": [
  {
   "title": "Products sold to date",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSQL": "SELECT count(op.order_products_id) as Units \nFROM order_products op\njoin orders o on op.order_id = o.order_id\nWHERE o.branch_location = '${Branch}'",
     "rawSql": "SELECT count(op.order_products_id) as Units \nFROM order_products op\njoin orders o on op.order_id = o.order_id\nWHERE o.branch_location = '${Branch}'",
     "schema": "public"
    }
   ]
  },
  {
   "title": "Product Volume over AVG",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSQL": "WITH BranchUnits AS (\n    SELECT COUNT(op.order_products_id) AS Units\n    FROM order_products op\n    JOIN orders o ON op.order_id = o.order_id\n    WHERE o.branch_location = '${Branch}'\n),\nTotalUnits AS (\n    SELECT COUNT(op.order_products_id) AS TotalUnits\n    FROM order_products op\n    JOIN orders o ON op.order_id = o.order_id\n),\nBranchCount AS (\n    SELECT COUNT(DISTINCT o.branch_location) AS BranchCount\n    FROM orders o\n)\nSELECT \n    ((CAST(BranchUnits.Units AS FLOAT) - (TotalUnits.TotalUnits / BranchCount.BranchCount)) / (TotalUnits.TotalUnits / BranchCount.BranchCount)) * 100.0 AS PercentageDif\nFROM \n    BranchUnits, \n    TotalUnits, \n    BranchCount;\n",
     "rawSql": "WITH BranchUnits AS (SELECT COUNT(op.order_products_id) AS Units\nFROM order_products op\nJOIN orders o ON op.order_id = o.order_id\nWHERE o.branch_location = '${Branch}'),\nTotalUnits AS (\n  SELECT COUNT(op.order_products_id) AS TotalUnits\n  FROM order_products op\n  JOIN orders o ON op.order_id = o.order_id\n  ),\n  BranchCount AS (\n    SELECT COUNT(DISTINCT o.branch_location) AS BranchCount\n    FROM orders o\n    )\n    SELECT(\n      (CAST(BranchUnits.Units AS FLOAT) - (TotalUnits.TotalUnits / BranchCount.BranchCount)) / (TotalUnits.TotalUnits / BranchCount.BranchCount)) * 100.0 AS PercentageDif\n      FROM BranchUnits,\n      TotalUnits,\n      BranchCount;",
     "schema": "public"
    }
   ]
  },
  {
   "title": "Branch Revenue to date",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSQL": "SELECT SUM(payment_total)/100 as Revenue FROM orders\nWHERE branch_location = '${Branch}'",
     "rawSql": "SELECT SUM(payment_total)/100 as Revenue FROM orders WHERE branch_location = '${Branch}'",
     "schema": "public"
    }
   ]
  },
  {
   "title": "Branch Revenue over AVG",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSQL": "WITH BranchRevenue AS (\n    SELECT SUM(payment_total) / 100.0 AS Revenue\n    FROM orders\n    WHERE branch_location = '${Branch}'\n),\nAverageRevenue AS (\n    SELECT SUM(payment_total) / (COUNT(DISTINCT branch_location) * 100.0) AS AvgRevenue\n    FROM orders\n)\nSELECT \n    (BranchRevenue.Revenue - AverageRevenue.AvgRevenue) / AverageRevenue.AvgRevenue * 100.0 AS PercentageDifference\nFROM \n    BranchRevenue, \n    AverageRevenue;\n",
     "rawSql": "WITH BranchRevenue AS (     SELECT SUM(payment_total) / 100.0 AS Revenue     FROM orders     WHERE branch_location = '${Branch}' ), AverageRevenue AS (     SELECT SUM(payment_total) / (COUNT(DISTINCT branch_location) * 100.0) AS AvgRevenue     FROM orders ) SELECT      (BranchRevenue.Revenue - AverageRevenue.AvgRevenue) / AverageRevenue.AvgRevenue * 100.0 AS PercentageDifference FROM      BranchRevenue,      AverageRevenue; ",
     "schema": "public"
    }
   ]
  },
  {
   "title": "Volume sold per product",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  p.name AS product,\n  COUNT(op.order_products_id) AS sales,\n  CAST(o.order_date AS TIMESTAMP) AS time\nFROM\n  order_products op\nJOIN\n  orders o ON op.order_id = o.order_id\nJOIN\n  products p ON op.product_id = p.product_id\nWHERE\n  o.branch_location = '${Branch}'\nGROUP BY\n  product,\n  time\nORDER BY\n  time;\n"
    }
   ]
  },
  {
   "title": "Product Volume sold",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSQL": "SELECT COUNT (op.order_products_id) AS volume,\nCAST(o.order_date AS TIMESTAMP) AS time\nFROM order_products op\nJOIN orders o ON op.order_id = o.order_id\nWHERE o.branch_location = '${Branch}'\nGROUP by time\nORDER BY time;",
     "rawSql": "SELECT COUNT (op.order_products_id) AS volume, CAST(o.order_date AS TIMESTAMP) AS time FROM order_products op JOIN orders o ON op.order_id = o.order_id WHERE o.branch_location = '${Branch}' GROUP by time ORDER BY time;"
    }
   ]
  },
  {
   "title": "Branch Revenue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSQL": "SELECT\r\n    CAST(order_date AS TIMESTAMP) AS time,\r\n    SUM(payment_total) / 100 AS revenue\r\nFROM\r\n    orders\r\n    WHERE branch_location = '${Branch}'\r\nGROUP BY\r\n    time\r\nORDER BY\r\n    time;\r\n\r\n",
     "rawSql": "SELECT     CAST(order_date AS TIMESTAMP) AS time,     SUM(payment_total) / 100 AS revenue FROM     orders     WHERE branch_location = '${Branch}' GROUP BY     time ORDER BY     time;  ",
     "schema": "public"
    }
   ]
  },
  {
   "title": "Product Volume sold per Hour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSQL": "SELECT\n    TO_CHAR(o.date_time, 'HH24:00') AS hour,\n    Count(op.order_products_id) AS volume\nFROM\n    orders o\nJOIN order_products op ON o.order_id = op.order_id\nWHERE o.branch_location = '${Branch}'\nGROUP BY\n    hour\nORDER BY\n    hour;",
     "rawSql": "SELECT     TO_CHAR(o.date_time, 'HH24:00') AS hour,     Count(op.order_products_id) AS volume FROM     orders o JOIN order_products op ON o.order_id = op.order_id WHERE o.branch_location = '${Branch}' GROUP BY     hour ORDER BY     hour;",
     "schema": "public"
    }
   ]
  },
  {
   "title": "Total Revenue per hour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSQL": "SELECT\r\n    TO_CHAR(o.date_time, 'HH24:00') AS hour,\r\n    SUM(payment_total/100) AS Revenue\r\nFROM\r\n    orders o\r\nWhere o.branch_location = '${Branch}'\r\nGROUP BY\r\n    hour\r\nORDER BY\r\n    hour;",
     "rawSql": "SELECT     TO_CHAR(o.date_time, 'HH24:00') AS hour,     SUM(payment_total/100) AS Revenue FROM     orders o Where o.branch_location = '${Branch}' GROUP BY     hour ORDER BY     hour;",
     "schema": "public"
    }
   ]
  },
  {
   "title": "Product sold per size per day ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSQL": "SELECT \n  p.size,\n  COUNT(op.product_id) AS Sold,\n  CAST(o.order_date AS TIMESTAMP) AS time\nFROM \n  order_products op\njoin\n  products p on op.product_id = p.product_id\njoin\n  orders o on op.order_id = o.order_id\nWHERE o.branch_location = '${Branch}'\nGroup by\n  p.size, time\nORDER BY\n  time ASC",
     "rawSql": "SELECT    p.size,   COUNT(op.product_id) AS Sold,   CAST(o.order_date AS TIMESTAMP) AS time FROM    order_products op join   products p on op.product_id = p.product_id join   orders o on op.order_id = o.order_id WHERE o.branch_location = '${Branch}' Group by   p.size, time ORDER BY   time ASC",
     "schema": "public"
    }
   ]
  },
  {
   "title": "Average order value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSQL": "SELECT (CONVERT(float, AVG(payment_total))/100) AS Order_Value, CAST(order_date AS TIMESTAMP) AS time\r\nFROM orders\r\nWHERE branch_location = '${Branch}'\r\nGROUP BY time",
     "rawSql": "SELECT \n  (AVG(payment_total) / 100) AS Order_Value, \n  CAST(order_date AS TIMESTAMP) AS time\nFROM \n  orders\nWHERE \n  branch_location = '${Branch}'\nGROUP BY \n  time\nORDER BY \n  time ASC;\n",
     "schema": "public"
    }
   ]
  }
 ]
}