services:

  db: 
    image: postgres
    container_name: postgres_service
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
    - ./grafana_provisioning/datasources:/etc/grafana/provisioning/datasources
    - ./grafana_provisioning/dashboard.yml:/etc/grafana/provisioning/dashboards/main.yml
    - ./grafana_provisioning/dashboards:/var/lib/grafana/dashboards
    depends_on:
    - db
volumes:
  grafana_data: