name: Deploy action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout-repo
        uses: actions/checkout@v2
      - name: Delete existing zip file
        run: |
          rm -rf .github/workflows/Cloudformation/extract_load_transform.zip
      
      - name: Zip files
        run: |
          pwd
          mkdir .github/workflows/Cloudformation/extract_load_transform
          cp src/extract_load_transform/get_connections.py .github/workflows/Cloudformation/extract_load_transform
          cp src/extract_load_transform/lambda_function.py .github/workflows/Cloudformation/extract_load_transform
          cd .github/workflows/Cloudformation
          zip -r extract_load_transform.zip extract_load_transform
          cd ../..
          pwd

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Upload zip file to S3
        run: |
          cd .github/workflows/Cloudformation
          aws s3 cp extract_load_transform.zip s3://bbb-cloudformation-deployment-packages
          sleep 3s

      - name: Deploy CloudFormation stack
      # get actual code from Kaelan especially the yaml location i assume from repo root?
        run: |
          aws cloudformation deploy \
            --template-file .github/workflows/Cloudformation/bbb-stack-template-S3.yml \
            --stack-name bbb-stack \
            --region eu-west-1
